### ISSUE TITLE
Change wifi test hostname to something other than irisbylowes.com

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#10]
The hub attempts to resolve irisbylowes.com as part of determing if there's wifi. This domain could end up being shut down, so change it to something more likely to stick around

https://github.com/arcus-smart-home/arcushubos/blob/master/meta-iris/recipes-core/iris-lib/files/irisdefs.h#L261

**Comment by pcouto64** [comment]
Yeah, I just noticed this myself.  I will change to something like google.com - just needs to be something that will resolve and is not likely to change again.

**Comment by pcouto64** [comment]
Changed this to google.com, hoping that will be around for a bit ;->
