### ISSUE TITLE
Change root password to something easier to copy

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#12]
The root password currently has symbols in it which often cause copy functionality in the user's browser or terminal to assume that the password is different words. This can be simplified by making the root password a passphrase, or a random series of 20 characters.

**Comment by pcouto64** [comment]
OK, that's a fair point.  In the past, we wanted this to not be the easiest thing to remember ;->  Personally, I've always used "sshpass" as a front-end to ssh/scp with the current hub password saved in my environment.  No need to cut/paste with this.

If you want to suggest a new password, I can certainly change the current one.  Thanks.

**Comment by AndrewX192** [comment]
Sure, I'll generate something - given that this is all public anyway, and one presumably *requires* a USB drive plugged into the hub, I'm not sure what threat(s) we're trying to address here. Certainly, for alternative (e.g. non-OSS) use cases, there may be a desire to keep the end-user out, but it seems like the best solution for that use case would be to change the password outside of this repo?

**Comment by pcouto64** [comment]
True - non-OSS cases should create new image build recipes and set a different password there.  Such recipes would not be added back to this repo.

**Comment by AndrewX192** [comment]
Password:
```
3XSgE27w5VJ3qvxK33dn
```
Hash:
```
$1$RM31Rd7b$8Ya4omyddgw5y9ozIU1eQ/
```

(again, the user must plug in a USB key with the appropriate debug file to use this password, if a user wishes to have debug mode enabled on their hub for production use, they need to change the password or use SSH keys instead. This is something that can be taken up in a future issue)

**Comment by pcouto64** [comment]
Updated the password as desired.  This is in the Yocto 2.7.1 branch at the moment - we used to update the password at major upgrade points.
