### ISSUE TITLE
Update to Yocto 3.0.x release

### ISSUE THREAD

**Issue by pcouto64** [arcus-smart-home/arcushubos#20]
A 3.0.1 release is out for this release stream.  In the past, I normally waited for the x.0.1 release to attempt a merge to make sure any initial kinks were worked out for the version.  Since this is a major release, it may require changes to the meta-iris code, so will likely take a bit more time than a standard point release update.

**Comment by AndrewX192** [comment]
Yocto 3.1 is now available: https://lists.yoctoproject.org/g/yocto-announce/message/186

**Comment by pcouto64** [comment]
Hi,

I noticed this as well recently.  I’ll try to find some time over the next weekend or two to try the upgrade.  Usually the major ones (from 2.x to 3.x) are a bit more time consuming…

Paul Couto
Couto Software Consulting, LLC
o: (617) 475-0750
c: (978) 430-9553

**Comment by AndrewX192** [comment]
Thanks! I was going to start on the yocto 2.7.3 upgrade and kernel upgrade, but if you're going to take on Yocto 3.1 I'll leave that alone!

**Comment by pcouto64** [comment]
I'm doing a quick upgrade to Yocto 2.7.4 today to pick up some openssl fixes.  There is a 3.1.x out now, will try to find time to play with that in the near future...

**Comment by pcouto64** [comment]
I created a PR for this today, wasn't as involved as I though it would be.  Now, there is a 3.1.1 release as well - I'll get to that at some point.  In the meanwhile, will create another issue to update the v3 kernel from 4.14.x to the 4.19.x LTS branch kernel.  This will take some patch updates and further testing than this 3.0.x upgrade involved.

**Comment by pcouto64** [comment]
I updated the yocto-3.0.x branch with the 3.0.4 release.  Not sure if anyone is that interested to make use of this, so will leave on a branch.  Still need to get to the 3.1.x Yocto release when I get a chance.
