### ISSUE TITLE
Update kernel to 4.19.115

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#25]
linux-yocto has a 4.19.115 release available per http://git.yoctoproject.org/cgit.cgi/linux-yocto/commit/?h=v4.19/standard/beaglebone&id=8e53093ba27fb7a714f62ad52c30031c3e0ae13d

**Comment by pcouto64** [comment]
Sure, I'll give this a try out later today.  I assume you built the 2.7.3 branch?  If that looked OK, I'll merge that in before I merge this.  Thanks.

**Comment by AndrewX192** [comment]
Forgot to link my pull request to the issue, fixed that now.

Yes, I built this on the 2.7.3 branch and verified on a V2 hub. In theory, it should also work on any 2.7 branch, as I believe this patch is applied against an artifact obtained based on the version in the `meta-iris/recipes-kernel/linux/linux-yocto_4.%.bbappend` file.

**Comment by pcouto64** [comment]
Thanks - I mainly wanted to check that you were able to build that 2.7.3 branch OK.  Switching to git modules sometimes causes headaches.

I applied this patch and built it as well.  Looks good.  I’ll merge in both PRs now.

Will try to get to the 3.x upgrade next weekend if I can.  I imagine it will be a bit more involved...

Paul Couto
Couto Software Consulting, LLC
o: (617) 475-0750
c: (978) 430-9553
