### ISSUE TITLE
Java truststore broken, potentially since Yocto 2.7

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#27]
This appears to have been broken for a while - not related to the changes over the last few days.

The Java system truststore is not available anymore, causing HTTPs clients to fail - in particular, this breaks updating HubOS over HTTPs via Arcus Platform.

Example program, that when run on the hub triggers the issue:

```
import java.net.URL;
import java.io.InputStream;

class Test {
   public static void main(String[] args) {
      try {
         InputStream inputStream = new URL("https://tools.arcus.wl-net.net/").openStream();
      } catch(Exception e) {
         System.out.println(e.toString());
      }

   }
}
```

Running this on the hub returns the following error, matching what shows up in the agent's log - this does not impact the ability to connect to Arcus Platform, as the system uses a different trust store included in iris2-system*.jar for that instead.

`javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

**Comment by AndrewX192** [comment]
Wondering if https://github.com/arcus-smart-home/arcushubos/commit/dcef151a70cb74f2626e0c122cbcbc51919436a9 is related?

**Comment by AndrewX192** [comment]
The following works:

```
java -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStore=/usr/lib/jvm/java-8-openjdk/jre/lib/security/cacerts Test
```

**Comment by AndrewX192** [comment]
Furthermore, it appears that you only need to set the password, not the trustStore location...

`java -Djavax.net.ssl.trustStorePassword=changeit Test`

**Comment by pcouto64** [comment]
I'll try to sort out this week - sorry if that change to clean up the recipe broke this

**Comment by AndrewX192** [comment]
I looked at this a bit more after my last comment. I don't think https://github.com/arcus-smart-home/arcushubos/commit/dcef151a70cb74f2626e0c122cbcbc51919436a9 is related - it seems that the JVM changed the default truststore password to "", but it doesn't seem possible to create a keystore with a empty password as keytool requires it to be 6 characters.

How about setting `javax.net.ssl.trustStorePassword=changeit` globally? I could easily add it to the iris-agent shell script

**Comment by pcouto64** [comment]
Sorry, have been away from this for a while due to fires with out volunteer work I do.  Yeah, this should be fixed in the iris-agent script.  I don't have time to test that at the moment, can you take care of the change and test in your environment?  Also, can you host agent builds at this point?  I think the last few ones I did I placed in my dropbox folder, which is fine for the near-term but wasn't meant to be a long-term solution.

**Comment by AndrewX192** [comment]
Ok, I'll push a change to the agent to set the keystore password. It seems a little backwards to do it there, but I'm at a loss for why it's happening at this point.

Can you open a ticket for self-hosting the agents? I'll pick that up in a few days and move it to the arcus tools site.

**Comment by pcouto64** [comment]
Thanks for taking care of this.  I created a new issue for the agent hosting - if you can provide a location, I’ll update the hubOS builds to make use of it.

I’m looking at the Yocto 3.0.x upgrade today.  Will likely create a PR with the changes if it proves to be not too bad.  The kernel for the v2 hub will remain the same as the Beagebone Black support hasn’t caught up to the one you upgraded to a while ago.

On the v3 side, there is likely a newer kernel, but I’m not sure if I’ll get to that upgrade today…

Paul Couto
Couto Software Consulting, LLC
o: (617) 475-0750
c: (978) 430-9553
