### ISSUE TITLE
Build fails due to specific versions of OpenJDK packages missing from Debian package repository. 

### ISSUE THREAD

**Issue by Zachs-Kappler** [arcus-smart-home/arcushubos#30]
The OpenJDK packages that are needed to compile for the hubv2 target have been replaced in Debian software repositories with version 8u265. This causes a 404 error and the build process is halted. These packages are still hosted on http://ftp.br.debian.org/, but who knows for how much longer until they get swapped out for the newer version.

**Comment by AndrewX192** [comment]
The solution to this is to bump the JDK to a newer version, as was done in #23. Feel free to open a pull request to bump the versions, otherwise I'll see if I can take care of it in a few days.

**Comment by pcouto64** [comment]
I'll take care of this later this week or over the weekend...

**Comment by pcouto64** [comment]
Just checked in an update to fix this.  Perhaps we should find another archive which keeps around older packages - I assumed Java8 would dead-end at some point, but it seems to keep going.

**Comment by pcouto64** [comment]
Hi,

I updated this today and also updated the Yocto 3.0.x branch to the latest 3.0.4 release.  At some point I’ll merge this branch to master if there is interested in an updated Yocto release.

Paul Couto
Couto Software Consulting, LLC
o: (617) 475-0750
c: (978) 430-9553

**Comment by AndrewX192** [comment]
OpenJDK 8 is currently planned to be supported through May 2026.
