### ISSUE TITLE
Update Java to 8u212

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#6]
Update Java to 8u212, which is precompiled for armhf: `openjdk-8-jdk-headless_8u212-b01-1_armhf.deb`. Unfortunately, this relies on glibc 2.28 which looks like a non-trivial upgrade.

**Comment by pcouto64** [comment]
The yocto upgrade to 2.7.x will get us to glibc 2.29.  This will be an easy change after that goes in.

**Comment by AndrewX192** [comment]
Pull request in #7. An easy change.

**Comment by pcouto64** [comment]
Thanks for fixing this as well.   Yeah, the Java 8 upgrades will be pretty trivial, just not sure how many more there will be.  Anything later will be a major project due to underlying changes in how the JVM is packaged, though.

**Comment by pcouto64** [comment]
A fix for this was just merged in
