### ISSUE TITLE
Agent does not have access to pwmchip0, can't play tones

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#8]
The arcus agent is unable to play tones on the IH200 as a result of not having permission to /sys/class/pwm/pwmchip0/ (specifically, the ability to read the directories)

```
$ ls -la /sys/class/pwm/pwmchip0/pwm1/
ls: /sys/class/pwm/pwmchip0/pwm1/.: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/..: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/period: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/power: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/duty_cycle: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/enable: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/capture: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/polarity: Permission denied
ls: /sys/class/pwm/pwmchip0/pwm1/uevent: Permission denied
```

a simple `chmod o+x /sys/class/pwm/pwmchip0/pwm1/` is sufficient to fix this issue.

looks like the fix belongs in `meta-iris/recipes-core/iris-utils/files/irisinit-ti`

**Comment by pcouto64** [comment]
Thanks for fixing this.  This must have been a 2.7.1 upgrade issue.  Often, with a  Yocto upgrade, weird stuff comes up here and there...

**Comment by pcouto64** [comment]
A fix was just merged in for this as well

**Comment by AndrewX192** [comment]
It was a fun bug to track down, I totally forgot the agent ran as non-root (which is good!) but immediately figured it out after trying to repro from the `agent` user
